version: '3'

services:
  fotd-front:
    container_name: 'fotd-front'
    build:
      context: ./front
    depends_on: [reverse-proxy]
    networks:
      - traefik_webgateway
    restart: unless-stopped
    ports:
      - "3000:80"
    labels:
      - 'traefik.enable=true'
      - "traefik.docker.network=traefik_webgateway"
      - "traefik.http.middlewares.force_https.redirectscheme.scheme=https"

      - 'traefik.http.routers.fotd-front.rule=Host(`flags.alexis-heroin.ca`)'
      - 'traefik.http.routers.front.tls=false'
      - 'traefik.http.routers.fotd-front.middlewares=fotd-front'
      - 'traefik.http.middlewares.fotd-front.chain.middlewares=force_https'
      - 'traefik.http.routers.fotd-front.service=fotd-front'
      - 'traefik.http.services.fotd-front.loadbalancer.server.port=80'

      - 'traefik.http.routers.front-tls.rule=Host(`flags.alexis-heroin.ca`)'
      - 'traefik.http.routers.front-tls.tls=true'
      - "traefik.http.routers.front-tls.tls.certresolver=le"
      - 'traefik.http.routers.front-tls.service=front-tls'
      - "traefik.http.services.front-tls.loadbalancer.server.port=80"

  fotd-api:
    container_name: 'fotd-api'
    build:
      context: ./back
    depends_on: [reverse-proxy]
    restart: unless-stopped
    networks:
      - traefik_webgateway
    ports:
      - "8082:8082"
    labels:
      - 'traefik.enable=true'
      - "traefik.docker.network=traefik_webgateway"
      - "traefik.http.middlewares.force_https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.rewrite_url.stripprefix.forceslash=true"

      - 'traefik.http.routers.fotd-api.rule=Host(`flags.alexis-heroin.ca`) && PathPrefix(`/api/`)'
      - 'traefik.http.routers.fotd-api.tls=false'
      - 'traefik.http.routers.fotd-api.service=fotd-api'
      - 'traefik.http.routers.fotd-api.middlewares=rewrite_url'
      - 'traefik.http.services.fotd-api.loadbalancer.server.port=8082'
      - 'traefik.http.middlewares.fotd-api.chain.middlewares=force_https, rewrite_url'

      - 'traefik.http.routers.api-tls.rule=Host(`flags.alexis-heroin.ca`) && PathPrefix(`/api/`)'
      - 'traefik.http.routers.api-tls.tls=true'
      - 'traefik.http.routers.api-tls.middlewares=rewrite_url'
      - "traefik.http.routers.api-tls.tls.certresolver=le"
      - 'traefik.http.routers.api-tls.service=api-tls'
      - "traefik.http.services.api-tls.loadbalancer.server.port=8082"
      - 'traefik.http.middlewares.api-tls.chain.middlewares=rewrite_url'

networks:
  traefik_webgateway:
    external: true
