version: '3'

services:
  fotd-front:
    container_name: 'fotd-front'
    build:
      context: ./front
    depends_on: [reverse-proxy]
    networks:
      - traefik_webgateway
    restart: unless-stopped
    ports:
      - "3000:80"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fotd-front.rule=Host(`flags.alexis-heroin.ca`)'
      - "traefik.http.routers.fotd-front.entrypoints=web"
      - 'traefik.http.services.fotd-front.loadbalancer.server.port=80'
      - "traefik.docker.network=traefik_webgateway"

  fotd-api:
    container_name: 'fotd-api'
    build:
      context: ./back
    depends_on: [reverse-proxy]
    restart: unless-stopped
    networks:
      - traefik_webgateway
    ports:
      - "8082:8082"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fotd-api.rule=Host(`flags.alexis-heroin.ca`) && PathPrefix(`/api`)'
      - "traefik.http.routers.fotd-api.entrypoints=web"
      - 'traefik.http.services.fotd-api.loadbalancer.server.port=8082'
      - "traefik.docker.network=traefik_webgateway"

networks:
  traefik_webgateway:
    external: true
